// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ONG_connect.Data;

#nullable disable

namespace ONG_connect.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260720141902_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ONG_connect.Models.Actividad", b =>
                {
                    b.Property<int>("IdActividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdActividad"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProyectoIdProyecto")
                        .HasColumnType("integer");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdActividad");

                    b.HasIndex("ProyectoIdProyecto");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("ONG_connect.Models.Beneficiario", b =>
                {
                    b.Property<int>("IdBeneficiario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBeneficiario"));

                    b.Property<decimal>("CantidadAyuda")
                        .HasColumnType("numeric");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProyectoIdProyecto")
                        .HasColumnType("integer");

                    b.Property<string>("TipoBeneficiario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdBeneficiario");

                    b.HasIndex("ProyectoIdProyecto");

                    b.ToTable("Beneficiarios");
                });

            modelBuilder.Entity("ONG_connect.Models.Donacion", b =>
                {
                    b.Property<int>("IdDonacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDonacion"));

                    b.Property<DateTime>("FechaDonacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("integer");

                    b.Property<string>("NombreDonante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProyectoIdProyecto")
                        .HasColumnType("integer");

                    b.Property<string>("TipoDonacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorEconomico")
                        .HasColumnType("numeric");

                    b.HasKey("IdDonacion");

                    b.HasIndex("ProyectoIdProyecto");

                    b.ToTable("Donaciones");
                });

            modelBuilder.Entity("ONG_connect.Models.Proyecto", b =>
                {
                    b.Property<int>("IdProyecto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProyecto"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Presupuesto")
                        .HasColumnType("numeric");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioIdUsuario")
                        .HasColumnType("integer");

                    b.HasKey("IdProyecto");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("ONG_connect.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ONG_connect.Models.Voluntario", b =>
                {
                    b.Property<int>("IdVoluntario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVoluntario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProyectoIdProyecto")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdVoluntario");

                    b.HasIndex("ProyectoIdProyecto");

                    b.ToTable("Voluntarios");
                });

            modelBuilder.Entity("ONG_connect.Models.Actividad", b =>
                {
                    b.HasOne("ONG_connect.Models.Proyecto", "Proyecto")
                        .WithMany("Actividades")
                        .HasForeignKey("ProyectoIdProyecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("ONG_connect.Models.Beneficiario", b =>
                {
                    b.HasOne("ONG_connect.Models.Proyecto", "Proyecto")
                        .WithMany("Beneficiarios")
                        .HasForeignKey("ProyectoIdProyecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("ONG_connect.Models.Donacion", b =>
                {
                    b.HasOne("ONG_connect.Models.Proyecto", "Proyecto")
                        .WithMany("Donaciones")
                        .HasForeignKey("ProyectoIdProyecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("ONG_connect.Models.Proyecto", b =>
                {
                    b.HasOne("ONG_connect.Models.Usuario", "Usuario")
                        .WithMany("Proyectos")
                        .HasForeignKey("UsuarioIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ONG_connect.Models.Voluntario", b =>
                {
                    b.HasOne("ONG_connect.Models.Proyecto", "Proyecto")
                        .WithMany("Voluntarios")
                        .HasForeignKey("ProyectoIdProyecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("ONG_connect.Models.Proyecto", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("Beneficiarios");

                    b.Navigation("Donaciones");

                    b.Navigation("Voluntarios");
                });

            modelBuilder.Entity("ONG_connect.Models.Usuario", b =>
                {
                    b.Navigation("Proyectos");
                });
#pragma warning restore 612, 618
        }
    }
}
